{
 "title": "service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"ReplicaSet\", namespace=\"default\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "[[pod]] - node" }
   ]
  },
  {
   "title": "Pod num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "[[pod]] - pod" }
   ]
  },
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu usage(avg 1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"^$pod.*\"}[1m]))",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod.*\"})by(pod)",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "network_receive_bytes/sec : eth0 (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{id=\"/\",interface=\"eth0\"}[1m])",
     "legendFormat": "{{kubernetes_io_hostname}} : {{interface}}"
    }
   ]
  },
  {
   "title": "network_transmit_bytes/sec : eth0 (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id=\"/\",interface=\"eth0\"}[1m])",
     "legendFormat": "{{kubernetes_io_hostname}} : {{interface}}"
    }
   ]
  },
  {
   "title": "tcp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP Sockets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{kubernetes_pod_name=~\".*$pod.*\", state!~\".*bytes\"}",
     "legendFormat": "{{kubernetes_pod_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "TCP Sockets - TIME_WAIT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_tcp_connection_states{state=\"time_wait\",kubernetes_pod_name=~\".*$pod.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "TCP Sockets - ESTABLISHED",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_tcp_connection_states{state=\"established\",kubernetes_pod_name=~\".*$pod.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}