apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-ops
data:
  prometheus.yml: |
    global: 
      scrape_interval: 15s 
      scrape_timeout: 15s 
    scrape_configs: 
    - job_name: exporter-descovery
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: pod
      scheme: http
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: pod_container_name
        regex: .*exporter
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: kubernetes_pod_container_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: kubernetes_pod_node_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: kubernetes_pod_name
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
        replacement: $1
        action: replace
        
    - job_name: kube-state-metrics
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

    - job_name: 'kubernetes-cadvisor'
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      follow_redirects: true
      enable_http2: true
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - separator: ;
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
        action: labelmap
      - source_labels: [__meta_kubernetes_node_name]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: /metrics/cadvisor
        action: replace
