apiVersion: v1
kind: Service
metadata:
  name: hello-demo
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
